
public class SpaceShip extends SpaceObject {

	public double[] thrust = new double[4];    //Instantaneous thrust generated by space ship, [x, y, z, t]
	
	public SpaceShip() {
		//Initialize thrust to all zeros
		for (int i=0; i<4; i++) {
			thrust[i] = 0;
		}
		
	}
	
	

}
